# Generated by Django 5.1.3 on 2024-12-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='sent/')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('is_received', models.BooleanField(default=False)),
            ],
        ),
    ]
